apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-storage
  namespace: exam
  labels:
    app: mongodb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

