version: "2"

services:
  frontend:
    image: localhost:5000/frontend.image
    build:
      context: ./exam-frontend
      dockerfile: Dockerfile
    container_name: frontend.container
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: localhost:5000/backend.image
    build:
      context: ./exam-backend
      dockerfile: Dockerfile
    container_name: backend.container
    ports:
      - "5000:5000"
    depends_on:
      - db
  db: 
    image: localhost:5000/mongo
    container_name: mongodb-service
